/* XPM */
static char *leave_selected[] = {
/* columns rows colors chars-per-pixel */
"149 79 5 1 ",
"  c #FF0000",
". c #FF4040",
"X c #FF8080",
"o c #FFBFBF",
"O c #FFFFFF",
/* pixels */
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                      OOOOOOOOOOOOOOOOOX  OOOOO       XOOOOX    XOOOOOOOOOOOOOOX    XOOOOOOOOOOOOOOX                                 ",
"                                      OOOOOOOOOOOOOOOOOX  OOOOO       XOOOOX    XOOOOOOOOOOOOOOX    XOOOOOOOOOOOOOOX                                 ",
"                                      OOOOOXXXXXXXXXXXX.  OOOOO       XOOOOX    .XXXXoOOOOoXXXX.    .XXXXoOOOOoXXXX.                                 ",
"                                      OOOOO               OOOOO       XOOOOX         XOOOOX              XOOOOX                                      ",
"                                      OOOOO               OOOOO       XOOOOX         XOOOOX              XOOOOX                                      ",
"                                      OOOOO                 XOOOOX  OOOOO            XOOOOX              XOOOOX                                      ",
"                                      OOOOO                 XOOOOX  OOOOO            XOOOOX              XOOOOX                                      ",
"                                      OOOOOXXXXXXXXXX       .XXOOoXXOOoXX            XOOOOX              XOOOOX                                      ",
"                                      OOOOOOOOOOOOOOO          OOOOOOOX              XOOOOX              XOOOOX                                      ",
"                                      OOOOOOOOOOOOOOO          OOOOOOOX              XOOOOX              XOOOOX                                      ",
"                                      OOOOO                 XOOOOX  OOOOO            XOOOOX              XOOOOX                                      ",
"                                      OOOOO                 XOOOOX  OOOOO            XOOOOX              XOOOOX                                      ",
"                                      OOOOO               XXoOOXX.  XXoOOXX.         XOOOOX              XOOOOX                                      ",
"                                      OOOOO               OOOOO       XOOOOX         XOOOOX              XOOOOX                                      ",
"                                      OOOOO               OOOOO       XOOOOX         XOOOOX              XOOOOX                                      ",
"                                      OOOOOOOOOOOOOOOOOX  OOOOO       XOOOOX    XOOOOOOOOOOOOOOX         XOOOOX                                      ",
"                                      OOOOOOOOOOOOOOOOOX  OOOOO       XOOOOX    XOOOOOOOOOOOOOOX         XOOOOX                                      ",
"                                      XXXXXXXXXXXXXXXXX.  XXXXX       .XXXX.    .XXXXXXXXXXXXXX.         .XXXX.                                      ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     ",
"                                                                                                                                                     "
};
